language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
  - python: "3.5"
    env: PYTHONASYNCIODEBUG=x
  - python: "3.6"
    env: PYTHONASYNCIODEBUG=x
  - python: "3.7"
    env: PYTHONASYNCIODEBUG=x
    dist: xenial
    sudo: true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: make check
after_success: coveralls
notifications:
  email: false
